### ISSUE TITLE
UndefVarError: coefnames not defined

### ISSUE THREAD

**Issue by IgorDouven** [dmbates/MixedModels.jl#106]
I'd like to explore the Mixed Models package, but I keep getting the same error message. Here is an example:

using DataFrames, MixedModels

df = DataFrame(Var1 = rand(100), Var2 = rand(100), Id = repeat(1:10, inner=10))

mm1 = fit!(lmm(@formula(Var1 ~ Var2 + (1 + Var2 | Id)), df))

The error I get is:

WARNING: both StatsBase and DataFrames export "coefnames"; uses of it in module MixedModels must be qualified
ERROR: UndefVarError: coefnames not defined
Stacktrace:
 [1] #lmm#16(::Array{Any,1}, ::Dict{Any,Any}, ::Distributions.Normal{Float64}, ::Function, ::DataFrames.Formula, ::DataFrames.DataFrame) at /Users/igor/.julia/v0.6/MixedModels/src/pls.jl:112
 [2] lmm(::DataFrames.Formula, ::DataFrames.DataFrame) at /Users/igor/.julia/v0.6/MixedModels/src/pls.jl:83

Here is the versioninfo()

Julia Version 0.6.1
Commit 0d7248e (2017-10-24 22:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

And Pkg.status("MixedModels") gives

MixedModels    0.13.0   master

**Comment by IgorDouven** [comment]
I was able to fix the problem by replacing two occurrences of 'coefnames' in pls.jl by 'DataFrames.coefnames'.

**Comment by andyreagan** [comment]
The issue is that StatsModels exported coefnames in 0.19.2

If the dependency for MixedModels is pinned at 0.19.0 (rather than 0.19) in the REQUIRE file this should fix this issue.
I can make this pull request but it might just be easier for @dmbates.

**Comment by andyreagan** [comment]
In the meantime, @IgorDouven you can fix this by just pinning stasbase:
    Pkg.pin("StatsBase",v"0.19.0")

**Comment by dmbates** [comment]
This is a direct consequence of changes in `StatsBase` and, indirectly, changes in `DataFrames`.

Note that your installed `MixedModels` is v0.13.0 and the most recent released version is v0.14.1, which depends on `DataFrames 0.11.0`.

The simplest fix is what you have done.  Longer term you will want to update to `DataFrames 0.11` which will allow many other packages to update.  It is tricky to do because you need to remove many packages that depend on `DataFrames` and are at versions that have an upper bound on the version of `DataFrames`.  My solution is to bite the bullet and remove my entire package directory then start by installing `DataFrames` and bring back all the other packages once you have the latest `DataFrames` installed.

We hope that cases like this where entire subsystems of the package system gets wedged will not occur after the release of julia 1.0

**Comment by dmbates** [comment]
I should have been more clear about fixing this once `DataFrames` is updated to 0.11.1

The Formula/ModelFrame/Contrasts/ModelMatrix system has been moved out of `DataFrames` into https://github.com/JuliaStats/StatsModels.jl

The currently released version (0.1.0) of `StatsModels` still gives an error but the "master" version fixes the problem.  I hope a new version of `StatsModels` will be released after https://github.com/JuliaStats/StatsModels.jl/pull/46 is incorporated.

**Comment by IgorDouven** [comment]
Thanks for the feedback -- much appreciated. I'll wait for Julia 1.0 to be released, then, after which I'll make a fresh start. In the meantime, I'm happy with the fix that is already working for me (and really happy with the MixedModels package so far -- thanks, Doug Bates, for creating this.)
