### ISSUE TITLE
rankUpdate! missing method and modeling question

### ISSUE THREAD

**Issue by Nosferican** [dmbates/MixedModels.jl#148]
I am trying to port some code from SAS in Patterson and Jones (2006).
The SAS code (ABE Example 3.1)

Set up
```
data ABEexample1;
input subject sequence$
formulation$ period AUC CMAX;
logauc = log(AUC);
logcmax = log(CMAX);
datalines;
1 RT R 1 2849 499
1 RT T 2 2230 436
2 TR T 1 2025 438
2 TR R 2 2000 361
3 TR T 1 2090 535
3 TR R 2 1826 558
4 RT R 1 2790 733
4 RT T 2 2864 416
5 RT R 1 2112 344
5 RT T 2 1744 48
6 TR T 1 2006 443
6 TR R 2 1881 681
7 TR T 1 2202 446
7 TR R 2 1935 481
8 RT R 1 1736 342
8 RT T 2 1882 437
9 RT R 1 1356 357
9 RT T 2 1175 240
10 TR T 1 1838 310
10 TR R 2 1602 340
11 RT R 1 1775 442
11 RT T 2 1585 286
12 TR T 1 1898 323
12 TR R 2 2504 331
15 TR T 1 1129 308
15 TR R 2 1036 243
16 RT R 1 2997 425
16 RT T 2 2237 332
17 RT R 1 1973 423
17 RT T 2 1778 407
18 TR T 1 2014 552
18 TR R 2 1938 427
19 RT R 1 1454 256
19 RT T 2 1297 348
20 TR T 1 1900 355
20 TR R 2 1730 401
21 RT R 1 2469 392
21 RT T 2 2023 480
22 TR T 1 1763 213
22 TR R 2 1472 177
23 TR T 1 1678 487
23 TR R 2 1336 412
24 RT R 1 1584 316
24 RT T 2 1855 373
25 RT R 1 4004 465
25 RT T 2 2449 625
26 TR T 1 2271 422
26 TR R 2 2389 731
27 TR T 1 1986 560
27 TR R 2 1857 461
28 RT R 1 1944 502
28 RT T 2 1593 326
29 RT R 1 1175 248
29 RT T 2 1147 221
30 TR T 1 2519 537
30 TR R 2 1941 400
31 RT R 1 1696 390
31 RT T 2 1801 350
34 RT R 1 1737 425
34 RT T 2 1655 319
35 TR T 1 1560 463
35 TR R 2 1629 372
36 RT R 1 2040 464
36 RT T 2 2199 384
;
run;
```
Code
```
proc mixed data = ABEexample1;
class sequence subject period formulation;
model logauc = sequence period formulation / ddfm = kenwardroger;
random subject(sequence);
lsmeans formulation / pdiff cl alpha = 0.1;
run;
```
I am trying to figure out how to translate `random subject(sequence)` to MixedModels syntax.
From the [docs](http://dmbates.github.io/MixedModels.jl/stable/MultipleTerms.html#A-Model-With-Nested-Random-Effects-1), I believe it is
```
model = fit(LinearMixedModel,
            @formula(logAUC ~ sequence + period + formulation + (1|sequence) + (1|subject)),
            data)
```
that leads to
```
MethodError: no method matching rankUpdate!(::LinearAlgebra.Diagonal{Float64, Vector{Float64}}, Matrix{Float64}, Float64)
```
I tried other combinations such as `(subject|sequence)`, `(sequence|subject)`, `(1|subject)` (since nested SAS model is the same), but none give the same
```
Covariance Parameter Estimates
------------------------------
Cov Parm           | Estimate
subject(sequence)  | 0.05157
residual           | 0.01100
```

1. Assuming I translated the SAS syntax correctly, then it would be a matter of addressing the missing method (related to #127?)
2. If not, how would it translate and the appropriate method to obtain the `subject(sequence)` Cov Parm estimate and
```
lsmeans formulation / pdiff cl alpha = 0.1;
```
(this is a bonus, and the formula or a reference should suffice if there isn't a canned method implemented).

**Comment by dmbates** [comment]
The error message relates to a symptom, not the actual problem.

A formula like `logAUC ~ sequence + period + formulation + (1|sequence) + (1|subject)` is not estimable because `sequence` occurs as a fixed-effects term and as a random effect.  It appears from the SAS output segment that is only one set of random effects and they are associated with `subject`.

In a way, this is related to #149 .  The specification `subject(sequence)` to me looks like it may mean "subject within sequence" or maybe "sequence within subject"  but both of those just amount to `(1|subject)` because each subject is exposed to only one sequence.

**Comment by dmbates** [comment]
I was able to fit this model using MixedModels yielding variance components of
```
julia> VarCorr(fm)
Variance components:
             Variance    Std.Dev.
 subject   0.048342963 0.219870332
 Residual  0.010313525 0.101555528
```

The reason these are different from those given by SAS is because they default to REML estimation of the variance components.  `MixedModels` uses maximum likelihood.  I have never bothered to add REML estimation to `MixedModels`.  It is possible to do that but I don't think it is as wonderful as many people assume.  The idea behind REML is that you want unbiased estimates of variance components and REML estimates have lower bias than ML estimates.  However, that assumes that bias is a good metric which, I submit, is not the case here.  The distribution of estimators of variances is obviously skewed to the right if you check a bootstrap sample or even if you remember from a first course in statistics that the distribution of S^2 is a chi-square.  It doesn't seem to me to be a good idea to try to get the mean of the estimator to be close to the parameter if you know that the mean is not a good representative value of the distribution (b/c of the skewness).

**Comment by Nosferican** [comment]
Thanks for the comments! I will go ahead and close this as the MethodError shouldn't be prevalent in most cases.
