### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by marynavickt** [dmbates/MixedModels.jl#166]
Is there a way to speed up fitting LinearMixedModel procedure by using some parallelization technique?  Cause it takes pretty much the same time on machines with 16 RAM + 4 cores and 256 RAM + 16 cores.

**Comment by dmbates** [comment]
Fitting a LinearMixedModel involves optimization of an objective with respect to parameters.  The optimization is an iterative process with each step consisting of choosing new values of the parameters, evaluating the objective at these new values, and checking for convergence.

The first thing to check is whether you are spending a lot of time in each iteration or you are doing a large number of iterations.  After fitting a model check the `optsum` property to find the number of iterations required, what the convergence criteria were, and which criterion resulted in convergence.

Alternatively use the optional argument `verbose=true` in the call to `fit!` to see the progress of the iterations.  This can tell you if it is a matter of each evaluation being slow or if the evaluations are fast but the number of iterations is very large.  Almost all the time in an iteration will be spent in `updateL!`.

An example using the `ml1m` data included with the package
```julia
julia> using BenchmarkTools, DataFrames, MixedModels, RData

julia> const dat = Dict(Symbol(k)=>v for (k,v) in load(joinpath(dirname(pathof(MixedModels)), "..", "test", "dat.rda")))

julia> ml1m = categorical!(dat[:ml1m], [:G, :H]);

julia> describe(ml1m)
3×8 DataFrame
│ Row │ variable │ mean    │ min │ median │ max  │ nunique │ nmissing │ eltype                         │
│     │ Symbol   │ Union…  │ Any │ Union… │ Any  │ Union…  │ Nothing  │ DataType                       │
├─────┼──────────┼─────────┼─────┼────────┼──────┼─────────┼──────────┼────────────────────────────────┤
│ 1   │ G        │         │ 1   │        │ 6040 │ 6040    │          │ CategoricalValue{Int32,UInt32} │
│ 2   │ H        │         │ 1   │        │ 3952 │ 3706    │          │ CategoricalValue{Int32,UInt32} │
│ 3   │ Y        │ 3.58156 │ 1.0 │ 4.0    │ 5.0  │         │          │ Float64                        │

julia> m1 = LinearMixedModel(@formula(Y ~ 1 + (1|G) + (1|H)), dat[:ml1m]);

julia> @btime updateL!(m1);
  1.096 s (93 allocations: 2.50 KiB)

julia> @time fit!(m1)
 33.509318 seconds (1.52 M allocations: 76.547 MiB, 0.07% gc time)
Linear mixed model fit by maximum likelihood
 Formula: Y ~ 1 + (1 | G) + (1 | H)
     logLik        -2 logLik          AIC             BIC       
 -1.33198601×10⁶  2.66397201×10⁶  2.66398001×10⁶  2.66402727×10⁶

Variance components:
              Column    Variance   Std.Dev.  
 G        (Intercept)  0.12985209 0.36034995
 H        (Intercept)  0.36879692 0.60728652
 Residual              0.81390868 0.90216887
 Number of obs: 1000209; levels of grouping factors: 6040, 3706

  Fixed-effects parameters:
             Estimate Std.Error z value P(>|z|)
(Intercept)   3.33902 0.0114624 291.302  <1e-99


julia> m1.optsum
Initial parameter vector: [1.0, 1.0]
Initial objective value:  2.6704109231589166e6

Optimizer (from NLopt):   LN_BOBYQA
Lower bounds:             [0.0, 0.0]
ftol_rel:                 1.0e-12
ftol_abs:                 1.0e-8
xtol_rel:                 0.0
xtol_abs:                 [1.0e-10, 1.0e-10]
initial_step:             [0.75, 0.75]
maxfeval:                 -1

Function evaluations:     29
Final parameter vector:   [0.39942627796568236, 0.6731406313870075]
Final objective value:    2.6639720116219684e6
Return code:              FTOL_REACHED
```

It takes about 1 second per call to `updateL!` and 29 function evaluations.  The total elapsed time of 33 seconds includes a bit of setup but almost all of it is in the `updateL!` calls.

If the calls to `updateL!` take only a few seconds you can profile an individual call
```julia
julia> using Profile

julia> @profile updateL!(m1)
```
I generally use the `ProfileView` package's `view` method to check the result.

In this case the result surprised me when I first saw it because the majority of the time is spent in `rankupdate!` when I had anticipated it would be in a dense Cholesky method.  Once I saw that it made sense because of the structure.
```julia
julia> describeblocks(m1)
1,1: Diagonal{Float64,Array{Float64,1}} (6040, 6040) Diagonal{Float64,Array{Float64,1}}
2,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (3706, 6040) SparseArrays.SparseMatrixCSC{Float64,Int32}
2,2: Diagonal{Float64,Array{Float64,1}} (3706, 3706) Array{Float64,2}
3,1: Array{Float64,2} (1, 6040) Array{Float64,2}
3,2: Array{Float64,2} (1, 3706) Array{Float64,2}
3,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,1: Array{Float64,2} (1, 6040) Array{Float64,2}
4,2: Array{Float64,2} (1, 3706) Array{Float64,2}
4,3: Array{Float64,2} (1, 1) Array{Float64,2}
4,4: Array{Float64,2} (1, 1) Array{Float64,2}
```
This shows the structure of the blocks in `A` and the corresponding blocks in `L`. `updateL!` performs a blocked Cholesky factorization to update L.  Because the (1,1) block is diagonal its factorization is very fast, even though its size is large.  The (2,1) block update will be fast because it just involves scaling the columns.  Almost all the time is spent in doing the rankupdate! of the (2,2) block from the (2,1) block.  This is a special type of matrix multiplication involving dense and sparse matrices.

Knowing this I can decide where to devote effort to make this faster.  Interestingly this is one of the few places where it would be possible to use multiple threads or perhaps GPU methods.
