### ISSUE TITLE
Issue with ranef function

### ISSUE THREAD

**Issue by jpadams16** [dmbates/MixedModels.jl#187]
Hi,

The ranef function no longer appears to be working fully. When fitting an LMM, using ranef works, unless the argument 'named=true' is included. When fitting a GLMM, ranef does not work at all. I receive the following error, "ERROR: MethodError: no method matching ranef(::GeneralizedLinearMixedModel{Float64})".

Using v2.0.0, I have tested on this toy example.
`N=50
x1 = repeat(1:N, outer=N)
x2 = repeat(1:N, inner=N)
x3 = sqrt.(1:N^2)
gg = repeat(1:50,inner=trunc(Int,N^2/50))
y = trunc.(Int, abs.(1 .- 2*x1 + 3*x2 + 0.5*x1.*x2 + rand(N^2) + x3.*rand(N^2)))
data = DataFrame(x1=x1, x2=x2, x3=x3, y=y, gg=gg)
categorical!(data, :gg)

LMM = fit!(LinearMixedModel(@formula(y ~ 1 + x1 + x2 + x3 + (1|gg)), data))
GLMM = fit!(GeneralizedLinearMixedModel(@formula(y ~ 1 + x1 + x2 + x3 + (1|gg)), data, Poisson()), fast=true)

ranef(LMM, named=true)
ranef(GLMM, named=true)`

Cheers.

**Comment by dmbates** [comment]
I temporarily turned off the ability to include the names with the random effects because it required a dependency on the `NamedArrays` package for that one use.  In some ways, the more dependencies that your package has the more difficult it is to maintain and I wanted to minimize the dependencies.

I was thinking that perhaps the [`LabelledArrays`](https://github.com/JuliaDiffEq/LabelledArrays.jl) package could be used instead but that package appears to have a different purpose.  I suppose the best thing is to reintroduce the dependency on `NamedArrays`.

**Comment by jpadams16** [comment]
Hi,

Thankyou for creating the patch, it appears to have fixed the instance of returning a named ranef array for Linear Mixed Models. But I still receive the error "ERROR: MethodError: no method matching ranef(::GeneralizedLinearMixedModel{Float64})" when using a Generalised Linear Mixed Model. I receive this error with and without the named argument,
ranef(GLMM) #returns error
ranef(GLMM, named=true) #returns error

Cheers,
Jamie

**Comment by jpadams16** [comment]
Hi @dmbates ,

Thankyou for creating the patch, it appears to have fixed the instance of returning a named ranef array for Linear Mixed Models. But I still receive the error "ERROR: MethodError: no method matching ranef(::GeneralizedLinearMixedModel{Float64})" when using a Generalised Linear Mixed Model. I receive this error with and without the named argument,
ranef(GLMM) #returns error
ranef(GLMM, named=true) #returns error

This is now using v2.1.2 with the same toy example.

Cheers,
Jamie
