### ISSUE TITLE
Drop variance column in random effects output?

### ISSUE THREAD

**Issue by vasishth** [dmbates/MixedModels.jl#213]
Unless there is some reason to keep it, I would like to suggest removing the variance column entirely in the random effects part of the output. I personally never look at it, I prefer to look at the SDs. It also confuses newcomers to see both a variance and an sd column. At least one person in every course I teach (almost) always asks why it's there.

**Comment by palday** [comment]
In lme4, you can actually choose -- it's just the default to display both. It wouldn't be hard to override the `show` method here to give that type of functionality, but I'm somewhat torn on the wisdom of changing the default behavior, especially since the random effects are labeled 'variance components'.

**Comment by dmbates** [comment]
I don't have strong opinions either way.  The source of confusion I fear is that users will interpret the `Std.Dev.` column as being the standard error of the estimate of the variance rather than the same estimate but on the standard deviation scale rather than the variance scale.

If we did decide to omit the variances, what should that section be labelled?  As @palday says, "Variance components" no longer seems appropriate.

**Comment by kliegl** [comment]
> If we did decide to omit the variances, what should that section be
labelled?
Square root of variance components?

I don't have a strong opinion either, but would vote in favor of keeping
it.  In teaching it allowed me to illustrate the difference between model
parameters and random effects (should they be renamed to conditional
modes?) .  The values also highlight differences in scales.

Am Mo., 7. Okt. 2019 um 18:03 Uhr schrieb Douglas Bates <
notifications@github.com>:
