### ISSUE TITLE
Extracting variance components

### ISSUE THREAD

**Issue by kxgao** [dmbates/MixedModels.jl#45]
I'm trying to save the estimated variance components of each random effect to some variable. However, using VarCorr, I'm only able to extract the error variance component. Is there a way to get the others?

Thank you.

**Comment by alansz** [comment]
I'm having the same issue, and finally figured it out, so I'm letting folks know here for reference.

My setup is R 3.5 with JuliaCall and Julia 1.1.1.

The goal is to get VarCorr(mm).σ, which is the vector of unscaled standard deviations of the random effects, in an R-useful way.

This works to get a Julia Array object: 

j$eval('VarCorr(fm2).\u03c3')

Because \u03c3 is how R conveys "unicode 03c3", which is the sigma symbol. On my system, at least, if I try j$eval('VarCorr(fm2).σ'), R treats the σ as an s and returns VarCorr(fm2).s instead, which means something else.

So for my model, which had only a single random intercept, what I needed was:

sigma<-j$eval('VarCorr(fm2).\u03c3[1]')
