### ISSUE TITLE
Nested grouping factors

### ISSUE THREAD

**Issue by JordanCuevas** [dmbates/MixedModels.jl#72]
I am in the process of moving my lme4 code from R over to Julia (those speed gains are very impressive), but I cannot find any documentation on the syntax. Specifically, I'm trying to specify nested random effects, but I cannot get it to work using the usual (1 | A/B) syntax. Is nesting supported natively in Julia MixedModels, or is the only solution to split nested effects into multiple terms: (1|A)+(1|A:B)?

**Comment by dmbates** [comment]
@JordanCuevas Yes.  In tact the preferred approach is to create the interaction factor in the Frame before fitting the model because A:B in Julia doesn't mean what it does in R.

Right now the whole CategoricalArrays/DataArrays/DataFrames/NullableArrays/StatsModels complex of packages is in the midst of a big redesign and it is not worthwhile devoting effort to building capabilities for the old version that will soon be replaced.

Creating the interaction factor can be a bit tricky, depending on what types A and B are.  Can you check

```jl
typeof(A), typeof(B)
```
and tell me what the result is?

**Comment by JordanCuevas** [comment]
A and B are made up variables for the purpose of my question. My real dataset has around 15 grouping factors, some of which will be nested, others crossed. All of them are in a DataFrame, and all are of type "String".

Regardless, I already went ahead and created new variables for my interaction factors in the DataFrame as you suggested and the model ran without problem.

**Comment by dmbates** [comment]
@JordanCuevas I'm glad it is working.  Once things settle down to using `CategoricalArrays` and `NullableArrays` throughout the `DataFrames` world I can look at making this easier to use.
